#pragma once
#ifdef KEYCODES_H
#define KEYCODES_H
#endif
#define SVAROG_KEY_SPACE 32
#define SVAROG_KEY_EXCL_PT 33
#define SVAROG_KEY_QUOTATION 34
#define SVAROG_KEY_HASHTAG 35
#define SVAROG_KEY_DLR_SIGN 36
#define SVAROG_KEY_PCT_SIGN 37
#define SVAROG_KEY_AND_SIGN 38
#define SVAROG_KEY_APST_SIGN 39
#define SVAROG_KEY_OPN_PTH 40
#define SVAROG_KEY_CLSE_PTH 41
#define SVAROG_KEY_MULT_SYM 42
#define SVAROG_KEY_ADD_SYM 43
#define SVAROG_KEY_COMMA 44
#define SVAROG_KEY_DASH_1 45
#define SVAROG_KEY_PERIOD 46
#define SVAROG_KEY_BACK_SLASH 47
#define SVAROG_KEY_NUM_1 48
#define SVAROG_KEY_NUM_2 49
#define SVAROG_KEY_NUM_3 50
#define SVAROG_KEY_NUM_4 51
#define SVAROG_KEY_NUM_5 52 
#define SVAROG_KEY_NUM_6 53 
#define SVAROG_KEY_NUM_7 54
#define SVAROG_KEY_NUM_8 55
#define SVAROG_KEY_NUM_9 56
#define SVAROG_KEY_NUM_0 57
#define SVAROG_KEY_DB_DT 58
#define SVAROG_KEY_SMI_CLN 59
#define SVAROG_KEY_LSN_SYM 60 // <
#define SVAROG_KEY_EQ_SYM 61 // =
#define SVAROG_KEY_GRN_SYM 62 // >
#define SVAROG_KEY_QS_SYM 63 // ? 
#define SVAROG_KEY_AT_SYM 64 // @ 
#define SVAROG_KEY_A 65
#define SVAROG_KEY_B 66
#define SVAROG_KEY_C 67
#define SVAROG_KEY_D 68
#define SVAROG_KEY_E 69
#define SVAROG_KEY_F 70
#define SVAROG_KEY_G 71 
#define SVAROG_KEY_H 72
#define SVAROG_KEY_I 73
#define SVAROG_KEY_J 74 
#define SVAROG_KEY_K 75
#define SVAROG_KEY_L 76
#define SVAROG_KEY_M 77
#define SVAROG_KEY_N 78
#define SVAROG_KEY_O 79
#define SVAROG_KEY_P 80 
#define SVAROG_KEY_Q 81
#define SVAROG_KEY_R 82
#define SVAROG_KEY_S 83
#define SVAROG_KEY_T 84
#define SVAROG_KEY_U 85 
#define SVAROG_KEY_V 86
#define SVAROG_KEY_W 87
#define SVAROG_KEY_X 88
#define SVAROG_KEY_Y 89
#define SVAROG_KEY_Z 90
// puncation keycodes 
#define SVAROG_KEY_FORWARD_BRACKET 91
#define SVAROG_KEY_FORWARD_SLASH 92
#define SVAROG_KEY_BACKWARDS_BRACKET 93
#define SVAROG_KEY_PW_SYM 94
#define SVAROG_KEY_DASH 95
#define SVAROG_KEY_APSTROPHE 96
// lowercase keycodes
#define SVAROG_KEY_l_A 97
#define SVAROG_KEY_l_B 98
#define SVAROG_KEY_l_C 99 
#define SVAROG_KEY_l_D 100
#define SVAROG_KEY_l_E 101
#define SVAROG_KEY_l_F 102 
#define SVAROG_KEY_l_G 103
#define SVAROG_KEY_l_H 104
#define SVAROG_KEY_l_I 105
#define SVAROG_KEY_l_J 106
#define SVAROG_KEY_l_K 107
#define SVAROG_KEY_l_L 108
#define SVAROG_KEY_l_M 109
#define SVAROG_KEY_l_N 110
#define SVAROG_KEY_l_O 111 
#define SVAROG_KEY_l_P 112
#define SVAROG_KEY_l_Q 113
#define SVAROG_KEY_l_R 114
#define SVAROG_KEY_l_S 115
#define SVAROG_KEY_l_T 116
#define SVAROG_KEY_l_U 117
#define SVAROG_KEY_l_V 118
#define SVAROG_KEY_l_W 119
#define SVAROG_KEY_l_X 120
#define SVAROG_KEY_l_Y 121
#define SVAROG_KEY_l_Z 122
// more puncation keycodes
#define SVAROG_KEY_BRACKET_1 123
#define SVAROG_KEY_DIV_SEP 124
#define SVAROG_KEY_BRACKET_2 125
#define SVAROG_KEY_SQUIGGLY 126 // Key refers to the ~ key