name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_libraries
      run: ./install_libraries.sh
    - name: build
      run: ./build.sh
